[package]
name = "maple-stdui"
version = "0.1.0"
authors = ["Andrey Tkachenko <andreytkachenko64@gmail.com>"]
edition = "2021"

[dependencies]
maple-macro = {path = "../maple-macro"}
maple-core = {path = "../maple-core"}
